 # This is a basic workflow to help you get started with Actions

name: Two Jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs: setup and build
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Run single line script
        run: echo Hallo, tutaj Łukasz Bola speaking!

      - name: Run python script
        run: python3 hello.py

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run single line script
        run: echo Hallo, tutaj Łukasz Bola speaking!
      - name: Run python script
        run: python3 hello.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Run single line script
        run: echo Hallo, tutaj Łukasz Bola speaking!
      - name: Run python script
        run: python3 hello.py
